#!/bin/bash
# Makes a randomized slideshow using feh

if [ "$1" = "-h" ] || [ $# -gt 1 ]; then
	echo "feh_pl [DURATION]"
	echo "builds randomized slideshow with all image files recursively found at cwd."
	echo "Default timer is 3s"
	exit 0
fi

if [ $# -gt 0 ]; then
	if ! echo "$@" | grep -Pi "^[0-9]+\.?[0-9]*$" &>/dev/null; then
		echo "$1 not a number!" 
		exit 1
	else
		echo "timer: $1 sec."
	fi
fi

extensions_pattern="png\|jpg\|jpeg"
files=()

while read -r line; do
files+=("$line")
done <<< $(/bin/find "$PWD" -type f | grep $extensions_pattern | sort -R)

timer=$1
if [ -z $1 ]; then
	echo timer unset, default is 3s
	timer=3
fi
/bin/feh --scale-down --slideshow-delay $timer "${files[@]}"&
